dh/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views                   #importing views from the 'user' app
from django.contrib.auth import views as auth_views     #importing authorized views for login and logout functionality

from django.conf import settings
from django.conf.urls.static import static              #used for static files

urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin'),
    path('register/', user_views.register, name = 'register'),                                              #the localhost will directly access the 'register' function in the 'views.py' in the 'users' app
    path('profile/<username>', user_views.profile, name = 'profile'),                                       #the localhost will directly access the 'profile' function in the 'views.py' in the 'users' app
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name = 'login'),               #the localhost will directly access the django's default login view
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name = 'logout'),           #the localhost will directly access the django's default logout view
    
    path('', include('forum.urls')),                                                                        #the localhost will redirect to the 'forum' app urls
    path('files/', include('files.urls')),                                                                  #the localhost will redirect to the 'files' app urls
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('upload', views.upload, name = 'files-upload'),                    #the 'upload' function in the views.py is called when localhost is called
    path('view', views.file_view, name = 'files-view'),                     #the 'file_view' function in the views.py is called when localhost is called
    path('view/delete-<pk>', views.delete_file, name = 'delete-file'),      #the 'delete_file' function in the views.py is called when localhost is called
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

files/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import os

def content_file_name(instance, filename):
    return '/'.join(['Storage', instance.user.username, filename])                                  #makes a folder with the usernme of the uploader followed by the file name

class File_Object(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)                                        #attaches the User table as a foreign key. models.CASCADE used to delete files after the user account is deleted
    name = models.CharField(max_length=255)                                                         #Simple char field for the name
    data = models.FileField(upload_to=content_file_name)                                            #stores the file into the server
    uploaded_on = models.DateTimeField(auto_now_add=True)                                           #sets to the current time and date when the post is created


    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):                                                              #deletes the file from the server along with it's entry in the database
        self.data.delete()
        super().delete(*args, **kwargs)

    @property
    def relative_path(self):
        return os.path.relpath(self.path, settings.MEDIA_ROOT)

files/forms.py
from django import forms
from .models import File_Object
from django.contrib.auth.models import User

class NewFileForm(forms.ModelForm):
    class Meta:
        model = File_Object
        fields = ['name', 'data']

files/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import NewFileForm
from .models import File_Object

@login_required
def upload(request):
    form = NewFileForm(request.POST, request.FILES)
    if request.method == 'POST':                                                                                #if block is executed is the POST request is recieved. Used to verify that data is recieved to be stored
        if form.is_valid():                                                                                     #if block is executed only if the form is valid
            data = form.save(commit=False)                                                                      #saves the form in a variable
            data.user = request.user                                                                            #set 'user' field to current user logged in
            data.save()                                                                                         #saves the form in the database
            messages.success(request, f"File has been uploaded successfully")                                   #sends a success message along with redirect to display in the page. Message block is stored in the 'base.html'
            return redirect('files-view')                                                                       #redirects to 'files-view' view
        else:
            messages.warning(request, f"Please fill all the fields given")                                      #sends a warning message along with redirect to display in the page. Message block is stored in the 'base.html'
            form = NewFileForm()                                                                                #reloads form
    return render(request, 'upload.html')                                                                       #request to render the upload.html file and sends the contex

@login_required
def file_view(request):
    context = {
        'files'     :   File_Object.objects.filter(user=request.user)                                           #filters all the files uploaded by logged in user
    }
    return render(request, 'file_list.html', context)                                                           #request to render the file_list.html file and sends the contex
    
@login_required
def delete_file(request, pk):
    if request.method == 'POST':                                                                                #if block is executed is the POST request is recieved.
        file = File_Object.objects.get(pk=pk)                                                                   #get selected object and stores it in file variable
        file.delete()                                                                                           #run delete function in models
        messages.success(request, f"The file has been deleted")                                                 #show message
    return redirect('files-view')                                                                               #redirects to 'files-view' view

files/templates/file_list.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  List
{% endblock %}

{% block content %}
{% if files %}
  {% for file in files %}
    <div class="card content-section mb-2">
      <div class="card-body p-3">
        <div class="row">
          <div class="col-10">
            Name of the file : <bold> {{ file.name }}  </bold><br>
            Uploaded on : {{ file.uploaded_on }}
            <textarea id="{{ file.name }}" style="position: absolute; left: -999em;">{{ file.data.url }}</textarea><br><br>
            <div class="mb-4">
              <table>
                <tr>
                  <td>
                    <a href="{{ file.data.url }}" download role="button">
                      <button class="ghost-green">Download</button>
                    </a>
                  </td>
                  <td>
                    <button class="ghost-blue" onclick="copyclip('{{ file.name }}');">Copy to clipboard</button>
                  </td>
                  <td>
                    <form method="post" action="{% url 'delete-file' file.pk %}">
                      {% csrf_token %}
                      <button type="submit" class="ghost-red">Delete File</button>
                    </form>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <script>
      function copyclip(link) {
        /* Get the text field */
        var copyText = document.getElementById(link);

        /* Select the text field */
        copyText.select();
        copyText.setSelectionRange(0, 99999); /*For mobile devices*/

        /* Copy the text inside the text field */
        document.execCommand("copy");

        /* Alert the copied text */
        alert("File Link has been copied to clipboard: " + copyText.value);
      }  
    </script>

  {% endfor %}
{% else %}
  <br>
  <h3>You have not uploaded any files</h3> <br>
  <a href="{% url 'files-upload' %}">
    <button class="ghost-blue">Upload now</button>
  </a>
{% endif %}

{% endblock content %}

files/templates/upload.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Upload
{% endblock %}

{% block content %}
<div class="container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_name">Name</label>
      <input type="text" class="form-control textinput" id="id_name" name="name">
    </div>
    <br>
    <div class="form-group">
      <label class="ghost-blue" for="id_data">Select a file to upload</label>
      <input type="file" class=" form-control" style="padding-bottom: 45px;" id="id_data" name="data">
    </div>
    <button type="submit" class="ghost-green">Upload</button>
  </form>
  <br><br><br>
  <p> <a href="{% url 'files-view' %}"><button class="ghost-pink">Views all uploads</button></a></p>
{% endblock content %}